// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using System.IO;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace LearningTrack
{
	public partial class InstructorStatisticsViewController : UIViewController
	{
		public InstructorStatisticsViewController (IntPtr handle) : base (handle)
		{
		}
		public override void DidReceiveMemoryWarning ()
		{
			// Releases the view if it doesn't have a superview.
			base.DidReceiveMemoryWarning ();
			// Release any cached data, images, etc that aren't in use.
		}
		
		#region View lifecycle
		
		public override void ViewDidLoad()
		{
			base.ViewDidLoad ();
			
			//Call to the following functions:
			//InitButtons();		//initialize button functions
			LoadDefaultPlot();//first action
		}

		void LoadDefaultPlot()
		{
			//link local filename to become a local HTML URL
			string fileName = "charts/gradeChart.htm"; // remember case-sensitive
			string localHtmlUrl = Path.Combine (NSBundle.MainBundle.BundlePath, fileName);
			//load the appropriate file to the webView
			webView.LoadRequest(new NSUrlRequest(new NSUrl(localHtmlUrl, false)));
			webView.ScalesPageToFit = false;

			//string url = "http://www.yahoo.com";
			//urlTextField.Text = url;
			//NSUrlRequest req = new NSUrlRequest (new NSUrl (url));
			//webView.LoadRequest (req);
		}
		
		void InitButtons()
		{
			refreshButton.Clicked += delegate { webView.Reload (); };
		}	
		#endregion
	}
}
