// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using System.IO;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.Dialog;
using System.Collections.Generic;

namespace LearningTrack
{
	public partial class InstructorSeatingChartViewController : UIViewController
	{
		public InstructorSeatingChartViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad ();
			
			//Load the first plot, for now
			LoadPlot();
			
			//Populate tableviews for plot selection
			//PopulateTableList();
		}

		public void LoadPlot (int plot = 0)
		{
			//link local filename to become a local HTML URL
			string  fileName;
			switch (plot) {
				//Remember case-sensitive
			case 0: fileName = "charts/SeatingCharts/morse.html"; break;
			case 1: fileName = "charts/barChart.htm"; break;
			case 2: fileName = "charts/gradeChart.htm"; break;
			case 3: fileName = "charts/gradeTrend.htm"; break;
			case 4: fileName = "charts/VsClassAverage.htm"; break;
			case 5: fileName = "charts/gradeDistribution.htm"; break;
			default: fileName = "charts/AttendanceChart.htm"; break;
			}
			string localHtmlUrl = Path.Combine (NSBundle.MainBundle.BundlePath, fileName);

			//load the appropriate file to the webView
			SeatWebView.LoadRequest(new NSUrlRequest(new NSUrl(localHtmlUrl, false)));
			SeatWebView.ScalesPageToFit = false;
			
		}

	}
}
