// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using System.Drawing;
using System.Collections.Generic;
using MonoTouch.UIKit;

namespace LearningTrack
{
	public partial class PickClassViewController : UIViewController
	{
		public PickClassViewController (IntPtr handle) : base (handle)
		{
		}
		UITableView table;
		public override void ViewDidLoad()
		{
			base.ViewDidLoad ();
			table = new UITableView(View.Bounds);
			table.AlwaysBounceVertical = true;
			Rectangle rect = new Rectangle(0, 0, 750, 900);
			table.Bounds = rect; 
		
			table.AutoresizingMask = UIViewAutoresizing.All;
			CreateTableItems();
			Add (table);

			bool isprofessor = true;
			bool isstudent = false;

			ContinueButton.Clicked += (sender, e) => {

				if(isprofessor)
				{
					this.PerformSegue("ToInstructorInterface", this);
				}
				else if (isstudent)
				{
					this.PerformSegue("ToStudentInterface", this);
				}
			};

		}
		protected void CreateTableItems ()
		{
			List<string> tableItems = new List<string> ();
			tableItems.Add ("EK 100");
			tableItems.Add ("PY 212");
			tableItems.Add ("EC 410");
			tableItems.Add ("EC 450");
			tableItems.Add ("EC 327");
			tableItems.Add ("EC 310");

			table.Source = new TableSource(tableItems.ToArray());
		}

	}
}
