// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using System.Drawing;
using System.Collections.Generic;
using MonoTouch.UIKit;

namespace LearningTrack
{
	public partial class PickClassViewController : UIViewController
	{
		public PickClassViewController (IntPtr handle) : base (handle)
		{
		}
		UITableView table;
		public override void ViewDidLoad()
		{
			base.ViewDidLoad ();

			//Defining table properties and implementing it
			table = new UITableView(View.Bounds);
			table.AlwaysBounceVertical = true;
			Rectangle rect = new Rectangle(0, 0, 750, 900);
			table.Bounds = rect; 
		
			table.AutoresizingMask = UIViewAutoresizing.All;
			CreateTableItems();
			Add (table);

			//Transition to interface depending on user privileges
			bool isProfessor = true;
			bool isStudent = false;

			ContinueButton.Clicked += (sender, e) => 
			{	
				if(isProfessor)
				{
					this.PerformSegue("ToInstructorInterface", this);
				}
				else if (isStudent)
				{
					this.PerformSegue("ToStudentInterface", this);
				}
			};

		}

		protected void CreateTableItems ()
		{
			//Create list of table items
			List<string> tableItems = new List<string> ();
			tableItems.Add ("EK 100");
			tableItems.Add ("PY 212");
			tableItems.Add ("EC 410");
			tableItems.Add ("EC 450");
			tableItems.Add ("EC 327");
			tableItems.Add ("EC 310");
			//Add table items from list to table
			table.Source = new TableSource(tableItems.ToArray());
		}
	}
}
