// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using MonoTouch.Foundation;
using System;
using System.Drawing;
using System.Collections.Generic;
using MonoTouch.UIKit;

namespace LearningTrack
{
	public partial class PickClassViewController : UIViewController
	{
		public bool isProfessor;
		public int chart;

		public PickClassViewController (IntPtr handle) : base (handle)
		{
			setChart(0);
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad ();

			CreateTableItems();

			//Transition to interface depending on user privileges
			ContinueButton.Clicked += (sender, e) => 
			{	
				if(isProfessor)
				{
					this.PerformSegue("ToInstructorInterface", this);
				}
				else
				{
					this.PerformSegue("ToStudentInterface", this);
				}
			};
		}

		protected void CreateTableItems ()
		{
			//Create list of table items
			List<string> tableItems = new List<string> ();
			tableItems.Add ("EK 100 [Lecture Hall]");
			tableItems.Add ("PY 212 [Studio Classroom]");
			//Add table items from list to table
			classTable.Source = new PickClassTableSource(tableItems.ToArray(), this);
		}

		//Set Chart value to be passed
		public void setChart (int chartValue){
			chart = chartValue;
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);
			//Make sure we are dealing with the appropriate segue
			if (segue.Identifier == "ToInstructorInterface") {
				// Get reference to the destination view controller
				var nextViewController = (InstructorTabBarController) segue.DestinationViewController;
				//Pass bool _isProfessor to the next view controller
				nextViewController.chartType = chart;
			}
			else if (segue.Identifier == "ToStudentInterface") {
				// Get reference to the destination view controller
				var nextViewController = (StudentTabBarController) segue.DestinationViewController;
				//Pass bool _isProfessor to the next view controller
				nextViewController.chartType = chart;
			}
		}
	}
}
