// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace LearningTrack
{
	public partial class SeatingChartWebView : UIView
	{
		public SeatingChartWebView (IntPtr handle) : base (handle)
		{
		}
	}
}
