// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using MonoTouch.Foundation;
using System;
using System.Drawing;
using System.Collections.Generic;
using MonoTouch.UIKit;

namespace LearningTrack
{
	public partial class StudentTabBarController : UITabBarController
	{
		public int chartType;
		
		public StudentTabBarController (IntPtr handle) : base (handle)
		{
		}
		
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			
			//Create UIViewController for Seating Chart reference
			StudentSeatingChartViewController seatingTab = (StudentSeatingChartViewController)this.ViewControllers[0];
			seatingTab.chartType = chartType;
		}
	}
}
