// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using System.IO;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace LearningTrack
{
	public partial class Student_StatisticsTabController : UIViewController
	{
		public Student_StatisticsTabController (IntPtr handle) : base (handle)
		{
		}

		public override void DidReceiveMemoryWarning ()
		{
			// Releases the view if it doesn't have a superview.
			base.DidReceiveMemoryWarning ();
			
			// Release any cached data, images, etc that aren't in use.
		}
		
		#region View lifecycle

		public override void ViewDidLoad()
		{
			base.ViewDidLoad ();

			//Call to the following functions:
			InitButtons();		//initialize button functions
			InitWebView ();		//initialize webview (not sure if needed)
			InitUrlTextField();	//initialize URL textfield function
			MakeFirstRequest ();//first action
		}
		
		void MakeFirstRequest ()
		{
			//link local filename to become a local HTML URL
			string fileName = "charts/index.htm"; // remember case-sensitive
			string localHtmlUrl = Path.Combine (NSBundle.MainBundle.BundlePath, fileName);
			//load the appropriate file to the webView
			webView.LoadRequest(new NSUrlRequest(new NSUrl(localHtmlUrl, false)));
			webView.ScalesPageToFit = false;

			//string url = "http://www.yahoo.com";
			//urlTextField.Text = url;
			//NSUrlRequest req = new NSUrlRequest (new NSUrl (url));
			//webView.LoadRequest (req);
		}
		
		void InitUrlTextField ()
		{
			//When return on the keyboard is pushed from the URL textfield, load link
			urlTextField.ShouldReturn = (textField) =>
			{
				urlTextField.ResignFirstResponder ();
				string url = urlTextField.Text;
				if (!url.StartsWith ("http://"))
				url = String.Format ("http://{0}", url);
				NSUrl nsurl = new NSUrl (url);
				NSUrlRequest req = new NSUrlRequest (nsurl);
				webView.LoadRequest (req);
				return true;
			};
		}

		void InitWebView ()
		{
			webView.LoadFinished += delegate { urlTextField.Text = webView.Request.Url.AbsoluteString; };
		}

		void InitButtons ()
		{
			refreshButton.TouchUpInside += delegate { webView.Reload (); };
		}	
		#endregion
	}
}
// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
